Repository fecgov/fec-proxy, pull requests merged in 2020-11, with the labels that each got.

#193 Implement cf cli v7, rolling deployment
  README.md
  manifest_dev.yml
  manifest_prod.yml
  manifest_stage.yml
Labels: Please review

#198 Add CircleCI integration for proxy
  .circleci/config.yml
  README.md
  bin/cf_deploy.sh
Labels: Before release

#196 Updates www redirects for PDFs made accessible
  redirects-www.conf
Labels: Before release, Please review

#194 Connect to CMS using internal routes
  README.md
  manifest_dev.yml
  manifest_prod.yml
  manifest_stage.yml
  nginx.conf
Labels: Before release, Please review

#201 Adds or updates certain transition redirects (based on new develop)
  redirects-transition.conf
Labels: Before release, Please review

#203 Court case page related redirects
  redirects-www.conf
Labels: Before release, Please review

#205 Remove direct application routes
  manifest_dev.yml
  manifest_prod.yml
  manifest_stage.yml
Labels: Before release, Please review

#206 redirect transition campaign finance statistical summary files
  redirects-transition.conf
Labels: Please review

#209 Add transition redirects for standalone court case pages
  redirects-transition.conf
Labels: Please review
