Repository fecgov/fec-proxy, pull requests merged in 2021-01, with the labels that each got.

#228 [MERGE WITH GIT FLOW] Release/public 20210105
  nginx.conf
  redirects-transition.conf
  redirects-www.conf
Labels: Please review

#235 [MERGE WITH GITFLOW] Release/public 20210119
  redirects-www.conf
Labels: release-branch

#234 Move to Nginx buildpack
  Staticfile
  manifest_dev.yml
  manifest_prod.yml
  manifest_stage.yml
  mime.types
  nginx.conf
Labels: Before release, Please review
