Repository fecgov/fec-proxy, pull requests merged in 2024-04, with the labels that each got.

#401 [MERGE WITH GITFLOW] Release/public 20240402
  redirects-transition.conf
Labels: Please review, release-branch

#402 [HOTFIX - MERGE WITH GITFLOW] Fix office transition page redirects
  redirects-transition.conf
Labels: hotfix

#403 Redirect eregs to ecfr
  redirects-e-regs.conf
Labels: Please review, Before release

#404 [MERGE WITH GITFLOW] Release/public 20240417
  redirects-e-regs.conf
Labels: release-branch
